Traceback (most recent call last):
  File "/home/david/Área de trabalho/projetos/NewVQVAE/Viewer.py", line 34, in <module>
    video = ReadDatas.readData("./data")[63]
  File "/home/david/Área de trabalho/projetos/NewVQVAE/readDatas.py", line 75, in readData
    data = np.load(folder+arq)
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './datadataH_3_5_14.npz'
Traceback (most recent call last):
  File "/home/david/Área de trabalho/projetos/NewVQVAE/Viewer.py", line 34, in <module>
    video = ReadDatas.readData("./data")[63]
  File "/home/david/Área de trabalho/projetos/NewVQVAE/readDatas.py", line 75, in readData
    data = np.load(folder+arq)
  File "/home/david/miniconda3/envs/VQVAE/lib/python3.10/site-packages/numpy/lib/_npyio_impl.py", line 455, in load
    fid = stack.enter_context(open(os.fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './datadataH_3_5_14.npz'
